Add info about blazor and namespaces
kysect/CodeStyle pull request #11
Opened 2022-01-25 19:58 UTC by FrediKats

2022-01-25 20:22 UTC, Bibletoon commented on blazor-specific.md
> +1. Для .razor страниц нужно явно namespaces
```suggestion
1. Для .razor страниц нужно явно указывать namespace
```

2022-01-25 20:22 UTC, Bibletoon commented on blazor-specific.md
> +   5. Указание базового класса от которого наследование идёт
```suggestion
   5. Указание базового класса от которого идёт наследование
```

2022-01-25 20:22 UTC, Bibletoon commented on blazor-specific.md
> +   6. Список внедряемых зависимостей
А точно ли это должно быть на самой странице, а не в .razor.cs файле? Туда-сюда бегать чтобы что-то заинжектить/посмотреть что заинжекшено не особо удобно

2022-01-25 20:22 UTC, Bibletoon commented on codestyle.md
> +9. Названия namespaces должны содержать только название проекта, не включать в себя папки. Чтобы не было конфликтов с анализаторами и Resharper,  в `ProjectName.csproj.DotSettings` можно прописать оп
Что-то не понял что имеется в виду. Можно пример неймспейса для условного SampleSolution/SampleProject/FolderA/FolderB/Class.cs

2022-01-25 21:58 UTC, annchous requested changes

2022-01-25 21:58 UTC, annchous commented on codestyle.md
> +9. Названия namespaces должны содержать только название проекта, не включать в себя папки. Чтобы не было конфликтов с анализаторами и Resharper,  в `ProjectName.csproj.DotSettings` можно прописать оп
```suggestion
9. Названия namespaces должны содержать только название проекта, не включать в себя папки. Чтобы не было конфликтов с анализаторами и Resharper, в `ProjectName.csproj.DotSettings` можно прописать опции NamespaceProvider = false. Сделать это можно в VS в свойствах папки.
```

2022-01-25 21:58 UTC, annchous commented on codestyle.md
> +9. Названия namespaces должны содержать только название проекта, не включать в себя папки. Чтобы не было конфликтов с анализаторами и Resharper,  в `ProjectName.csproj.DotSettings` можно прописать оп
Не учитывать название папки в неймспейсе.
Ответ на твой вопрос:
SampleSolution.SampleProject

2022-01-25 21:58 UTC, annchous commented on blazor-specific.md
> +   3. Указание текущего namespaces
```suggestion
   3. Указание текущего namespace
```

2022-02-05 08:34 UTC, FrediKats commented on blazor-specific.md
> +   6. Список внедряемых зависимостей
Эмнип, там какая-то дичь была с тем, что в .razor.cs инжектится всё очень криво, а в файл около нормально. Я заведу ишую, чтобы поресёрчить.

2022-02-05 08:35 UTC, merged