Add codestyle rules from OOP
kysect/CodeStyle pull request #8
Opened 2022-01-03 10:23 UTC by FrediKats

close #7 
ref to #6 
close #5

2022-01-03 10:58 UTC, I-SER-I commented on codestyle.md
> +8.  Используйте Type.Parse вместо Conver.ToType (например, int.Parse вместо Convert.ToInt32)
```suggestion
8.  Используйте Type.Parse вместо Convert.ToType (например, int.Parse вместо Convert.ToInt32)
```

2022-01-03 11:01 UTC, I-SER-I commented on solution-structure.md
> +    - *feature-name*TestCaseContext - тулзовый класс, который содержит методы генерации нужных данных для тестов
Logger куда пихать?)
И прочие Utilites

2022-01-03 11:08 UTC, lipa44 commented on suggestions.md
> +1. Сериализуемые dto должны иметь приватные сеттеры
Как насчёт `init` и/или `record` вместо `class`, если объект используется только для передачи информации и должен быть иммутабельным?

2022-01-03 11:24 UTC, I-SER-I commented on suggestions.md
> +1. Сериализуемые dto должны иметь приватные сеттеры
`record` имутабелен)

2022-01-03 11:25 UTC, lipa44 commented on suggestions.md
> +1. Сериализуемые dto должны иметь приватные сеттеры
Ну так о том и речь, тут сказано использовать приватные сеты вместо того, чтобы заюзать record

2022-01-03 11:52 UTC, I-SER-I commented on suggestions.md
> +1. Сериализуемые dto должны иметь приватные сеттеры
А понял о чем ты, ну да `init` спросить забыли. Хотя там разница особо не велика

2022-01-03 12:23 UTC, ronimizy commented on codestyle.md
> +10. Не используйте оператор== для сравнения не числовых типов. Не переопределяйте оператор== для не числовых типов
```suggestion
10. Не используйте оператор `==` для сравнения не числовых типов. Не переопределяйте оператор `==` для не числовых типов
```

2022-01-03 12:28 UTC, ronimizy commented on codestyle.md
> +6. При написании chain of call, разделяйте каждый вызов на отдельную строку
Такая формулировка может быть не очевидна для новичков, которые не знают про что это правило

```suggestion
6. При написании цепочки вызовов методов, разделяйте каждый вызов на отдельную строку
```

2022-01-03 12:31 UTC, ronimizy commented on suggestions.md
> +2. Для валидной конвертации из сущности в dto нужно писать мапперы - `Expression<Func<TEntity, TDto>>`. Они должны напрямую сетить все нужные поля и не использовать конструкторы или статические метод
ничья
```suggestion
1. Сериализуемые dto должны иметь приватные сеттеры
2. Сериализуемые dto должны иметь публичный пустой конструктор
3. Для валидной конвертации из сущности в dto нужно писать мапперы - `Expression<Func<TEntity, TDto>>`. Они должны напрямую сетить все нужные поля и не использовать конструкторы или статические методы.
```

2022-01-03 12:33 UTC, ronimizy commented on suggestions.md
> +1. Сериализуемые dto должны иметь публичный пустой конструктор
Вообще, звучит будто "Dto должны быть сериализуемы"

2022-01-03 12:39 UTC, ronimizy commented on suggestions.md
> +2. Для валидной конвертации из сущности в dto нужно писать мапперы - `Expression<Func<TEntity, TDto>>`. Они должны напрямую сетить все нужные поля и не использовать конструкторы или статические метод
А вот это вообще не совсем понял, пояснительную бригаду пж

2022-01-03 12:43 UTC, xrem commented on suggestions.md
> +1. Сериализуемые dto должны иметь публичный пустой конструктор
Если в качестве Dto будут простые POCO, то никакой проблемы нет

2022-01-03 13:04 UTC, Bibletoon requested changes

2022-01-03 13:04 UTC, Bibletoon commented on solution-structure.md
> +    - EntityGenerators - генераторый фейковых данных для демо
```suggestion
    - EntityGenerators - генераторы фейковых данных для демо
```

2022-01-03 13:04 UTC, Bibletoon commented on solution-structure.md
> +      - *entity-name*Dto.cs - модель, которая врапит сущность для возвращения entity с API
```suggestion
      - *entity-name*Dto.cs - модель, которая оборачивает сущность для возвращения entity с API
```

2022-01-03 13:06 UTC, Bibletoon commented on suggestions.md
> +2. Для валидной конвертации из сущности в dto нужно писать мапперы - `Expression<Func<TEntity, TDto>>`. Они должны напрямую сетить все нужные поля и не использовать конструкторы или статические метод
Маркдауну кстати всё равно на то, что дважды первый пункт написан, при рендеринге от выдаст правильные номера пунктов

2022-01-03 14:10 UTC, annchous commented on codestyle.md
> +6. При написании chain of call, разделяйте каждый вызов на отдельную строку
Надеюсь, что эти новички хотя бы знают, что такое гугл и переводчик)

2022-01-03 14:20 UTC, annchous reviewed
Иногда стоят точки в конце пунктов, а иногда нет. Привести к единому стилю.

2022-01-03 14:20 UTC, annchous commented on codestyle.md
> +## Abstract
```suggestion
## General
```

2022-01-03 14:20 UTC, annchous commented on codestyle.md
> +1. Основной нейминга является кодстайл майкрософта: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines
```suggestion
1. Основой нейминга является кодстайл майкрософта: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines
```

2022-01-03 14:20 UTC, annchous commented on codestyle.md
> +2. Имена должны быть читабельными и понятными, без сокращений, аббревиатур и грамматических ошибок. Исключение – общепринятые сокращения, напр. i, j, k в циклах.
Про аббревиатуры неправда же. Db, Html, ~~Sobr, Vbr~~...

2022-01-03 16:28 UTC, FrediKats commented on solution-structure.md
> +    - *feature-name*TestCaseContext - тулзовый класс, который содержит методы генерации нужных данных для тестов
Дописал.

2022-01-03 16:33 UTC, FrediKats commented on suggestions.md
> +1. Сериализуемые dto должны иметь приватные сеттеры
Поправил, спасибо.

2022-01-03 16:35 UTC, FrediKats commented on suggestions.md
> +2. Для валидной конвертации из сущности в dto нужно писать мапперы - `Expression<Func<TEntity, TDto>>`. Они должны напрямую сетить все нужные поля и не использовать конструкторы или статические метод
Исправил, спасибо.

2022-01-03 16:35 UTC, FrediKats commented on suggestions.md
> +1. Сериализуемые dto должны иметь публичный пустой конструктор
Ну, я так написал, что они должны быть рекордами. Думаю, этого достаточно)

2022-01-03 16:37 UTC, FrediKats commented on suggestions.md
> +2. Для валидной конвертации из сущности в dto нужно писать мапперы - `Expression<Func<TEntity, TDto>>`. Они должны напрямую сетить все нужные поля и не использовать конструкторы или статические метод
Уф, это приколы с мапингом ответов от EF'а. Чтобы нормально селектить ответ EF в DTO, нужно передавать лямбду, которая селектит и создаёт объект нужный. При этом оно всё ломается об конструкторы и методы статические.

2022-01-03 16:39 UTC, FrediKats commented on codestyle.md
> +4. Если метод должен вернуть коллекцию, но нет элементов, то должна возвращаться пустая коллекция, а не null значение вместо коллекции.
Fixed

2022-01-03 16:42 UTC, FrediKats commented on codestyle.md
> +8.  Используйте Type.Parse вместо Conver.ToType (например, int.Parse вместо Convert.ToInt32)
Fixed

2022-01-03 16:44 UTC, FrediKats commented on codestyle.md
> +6. При написании chain of call, разделяйте каждый вызов на отдельную строку
Fixed

2022-01-03 16:44 UTC, lipa44 commented on suggestions.md
> +1. Для простых DTO (моделей, описание реквестов и респонсов в CQRS), где это возможно, стоит использовать `record`.
Точно ли стоит упоминать CQRS в саджестах для всех студентов?)

2022-01-03 16:45 UTC, FrediKats commented on codestyle.md
> +9. Не пишите в лямбдках больше одной операции, выносите сложную логику в методы
Так тоже было неплохо!

2022-01-03 16:46 UTC, FrediKats commented on codestyle.md
> +10. Не используйте char, short памяти. Большинство интерфейсов работают с int, а значит в коде появится много кастов, которые усложняют код.
Да, случайно кусок текста остался в голове автора.

2022-01-03 16:47 UTC, FrediKats commented on solution-structure.md
> +    - EntityGenerators - генераторый фейковых данных для демо
Out dated

2022-01-03 16:48 UTC, FrediKats commented on solution-structure.md
> +      - *entity-name*Dto.cs - модель, которая врапит сущность для возвращения entity с API
Outdated

2022-01-03 16:49 UTC, FrediKats commented on suggestions.md
> +1. Для простых DTO (моделей, описание реквестов и респонсов в CQRS), где это возможно, стоит использовать `record`.
Все мы так будем...

2022-01-03 16:50 UTC, FrediKats commented on codestyle.md
> +2. Имена должны быть читабельными и понятными, без сокращений, аббревиатур и грамматических ошибок. Исключение – общепринятые сокращения, напр. i, j, k в циклах.
Fixed

2022-01-03 16:54 UTC, FrediKats commented on suggestions.md
> +1. Для простых DTO (моделей, описание реквестов и респонсов в CQRS), где это возможно, стоит использовать `record`.
Fixed

2022-01-03 16:55 UTC, FrediKats commented
.

2022-01-03 16:55 UTC, FrediKats commented
Можно по второму кругу. Ну или буду ждать от вас апдейтов уже отдельными реквестами.

2022-01-03 19:52 UTC, luck-o-o-luck reviewed
Прошлась по ошибкам в самом тексте + предложение с подпунктами (ставлять их и без точек, и без других знаков препинания - грустная ситуация, кмк)

2022-01-03 19:52 UTC, luck-o-o-luck commented on codestyle.md
> +   1. Валидация аргументов
Почему после подпункта не ставим ";"?

2022-01-03 19:52 UTC, luck-o-o-luck commented on codestyle.md
> +   4. Инициализация, которая требует какой-то логики, вызовов методов
Ну и в последнем точка, если добавлять ";". Кажется, так будет выглядеть аккуратнее и солиднее.

2022-01-03 19:52 UTC, luck-o-o-luck commented on codestyle.md
> +2. Для ошибок бизнес логики стоит бросать кастомный эксепшен. Для стандартных ошибок, например невалидных аргументов, стоит использовать стандартные типы.
```suggestion
2. Для ошибок бизнес логики стоит бросать кастомный эксепшен. Для стандартных ошибок, например, невалидных аргументов, стоит использовать стандартные типы.
```

2022-01-03 19:52 UTC, luck-o-o-luck commented on codestyle.md
> +4. Не оставляйте мутабельные поля для отложенной инициализации. Инициализируйте поля в конструкторах и делайте иммутабельные поля и свойства где это уместно.
```suggestion
4. Не оставляйте мутабельные поля для отложенной инициализации. Инициализируйте поля в конструкторах и делайте иммутабельные поля и свойства, где это уместно.
```

2022-01-03 19:52 UTC, luck-o-o-luck commented on codestyle.md
> +5. Если возникает ошибка при валидации аргументов, то нужно указывать какой именно аргумент приводит к ошибке в тексте ошибки.
```suggestion
5. Если возникает ошибка при валидации аргументов, то нужно указывать, какой именно аргумент приводит к ошибке в тексте ошибки.
```

2022-01-03 19:52 UTC, luck-o-o-luck commented on codestyle.md
> +4. Избегайте кастов там, где можно их не использовать. Программа должна стримиться к повышению типизации и увеличении количества мест, где происходят проверки во время компиляции.
```suggestion
4. Избегайте кастов там, где можно их не использовать. Программа должна стремиться к повышению типизации и увеличению количества мест, где происходят проверки во время компиляции.
```

2022-01-03 19:52 UTC, luck-o-o-luck commented on suggestions.md
> +3. Не пишите сложную логику поверх примитивных типов, вводите информативные обёртки в которых можно инкапсулировать валидацию и логику.
```suggestion
3. Не пишите сложную логику поверх примитивных типов, вводите информативные обёртки, в которых можно инкапсулировать валидацию и логику.
```

2022-01-03 22:33 UTC, luck-o-o-luck commented on codestyle.md
> +   4. Инициализация, которая требует какой-то логики, вызовов методов
Если что, я могу этим заняться. Кмк, точка сюда не оч подойдет как раз из-за того, что это не самостоятельные части предложения, а обычное перечисление. Было бы хорошо использовать ";", но я бы ещё с Аней посоветовалась по этому поводу.

2022-01-04 06:01 UTC, FrediKats commented
Как-то уж слишком много выходит всяких знаков(

2022-01-04 06:02 UTC, FrediKats commented
Крч, жду на остальное в ишуях и пул реквестах.

2022-01-04 06:02 UTC, merged