Refactor readme
kysect/CodeStyle pull request #9
Opened 2022-01-04 08:30 UTC by luck-o-o-luck

Исправила ошибки и добавила знаки препинания. Чекайте

2022-01-04 08:51 UTC, luck-o-o-luck commented on README.md
> +   + Если стиль уже существует, прикрепить [пермалинк](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) существующих п
```suggestion
   + Если стиль уже существует, прикрепить [пермалинк](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) существующих правил и сэмплов кода к дискуссии.
```

2022-01-04 13:37 UTC, I-SER-I commented on README.md
> +   + Если стиль уже существует, прикрепить [пермалинк](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) существующих п
![image](https://user-images.githubusercontent.com/50848091/148067277-944631d5-11ac-474d-bcb2-45656bb0318a.png)

2022-01-04 13:43 UTC, ALEXXXANDRO requested changes

2022-01-04 13:43 UTC, ALEXXXANDRO commented on README.md
> +Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напартачили, такой пр не будет вмержен. \
Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напортачили, такой пр не будет вмерджен. \

2022-01-04 13:46 UTC, luck-o-o-luck commented on README.md
> +Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напартачили, такой пр не будет вмержен. \
```suggestion
Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напортачили, такой пр не будет вмержен. \
```

2022-01-04 13:53 UTC, luck-o-o-luck commented on README.md
> +У пр после принятия стиля не должно быть диффа, не относящегося к ситуациеи его применения.
```suggestion
У пр после принятия стиля не должно быть диффа, не относящегося к ситуации его применения.
```

2022-01-04 17:00 UTC, ronimizy requested changes

2022-01-04 17:00 UTC, ronimizy commented on README.md
> +У пр после принятия стиля не должно быть диффа, не относящегося к ситуации его применения.
"По принятию" значит цель пр. 
По какому вопросу создан пр? По принятию стиля в нашу семью кодстайла.

2022-01-05 08:20 UTC, luck-o-o-luck commented on README.md
> +У пр после принятия стиля не должно быть диффа, не относящегося к ситуации его применения.
А, пон, тогда лучше переписать предложение - есть двусмысленность

2022-01-05 08:21 UTC, luck-o-o-luck commented on README.md
> +Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напортачили, такой пр не будет вмерджен. \
> Откуда `д` в слове `merge`?

Потому что существует слово мердж. Мердж двух точек и т.д.

2022-01-07 21:50 UTC, luck-o-o-luck commented on README.md
> +У пр после принятия стиля не должно быть диффа, не относящегося к ситуации его применения.
```suggestion
У пр по принятию стиля не должно быть диффа, не относящегося к ситуации его применения.
```

2022-01-08 09:45 UTC, FrediKats approved these changes

2022-01-08 09:46 UTC, ronimizy approved these changes

2022-01-08 09:52 UTC, annchous requested changes

2022-01-08 09:52 UTC, annchous commented on README.md
> +Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напортачили, такой пр не будет вмерджен. \
<img width="81" alt="image" src="https://user-images.githubusercontent.com/57408376/148639778-2ac17168-ed76-4969-958b-7498bfc79c12.png">
А буква ё где...

2022-01-08 09:52 UTC, annchous commented on README.md
> +У пр по принятию стиля не должно быть диффа, не относящегося к ситуации его применения.
```suggestion
Пулл-реквест с внесением предложений по стилю не должен содержать изменений, не относящихся к области применения предлагаемого стиля.
```

2022-01-08 09:53 UTC, ronimizy commented on README.md
> +Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напортачили, такой пр не будет вмерджен. \
вмерджён

2022-01-08 10:39 UTC, luck-o-o-luck commented on README.md
> +Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напортачили, такой пр не будет вмерджен. \
```suggestion
Если ваш пр имеет в себе изменения, не связанные с описанной ситуацией применения стилей, то вы где-то напортачили, такой пр не будет вмёрджен. \
```

2022-01-08 11:52 UTC, annchous approved these changes

2022-01-08 17:42 UTC, merged